# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish to readthedocs

on: workflow_dispatch

permissions:
  pull-requests: write
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
#       - name: Install docs dependencies
#         run: |
#           pip install -r requirements-docs.txt
#           sudo apt-get update
#           sudo apt install --yes pandoc
#           npm install @mermaid-js/mermaid-cli
      - name: Build docs
        env:
          SPHINX_MERMAID_NO_SANDBOX: 1
          NOTEBOOK_FAST_RUN: 1
        run: |
          cd docs
          make html
          cd ..
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html # The folder the action should deploy.
